dist: trusty
sudo: required
language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2/repository

branches:
  only:
    - master
    - /release\/.*/

install: travis_retry mvn install -DskipTests=true -B -V

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: "Build and test"
      script: travis_retry mvn test
    - stage: release
      name: "Push to Nexus"
      if: fork = false AND (branch = master OR branch =~ /release\/.*/) AND type != pull_request
      before_install:
        - "cp .travis.settings.xml $HOME/.m2/settings.xml"
      script:
        # Use full history for release
        - git checkout -B "${TRAVIS_BRANCH}"
        # Skip building of release commits
        - mvn --batch-mode  -DscmCommentPrefix="[maven-release-plugin][skip ci] " -Dusername="${GIT_USERNAME}" -Dpassword="${GIT_PASSWORD}" -DskipTests -Darguments=-DskipTests release:clean release:prepare release:perform
