# -*- mode: ruby -*-
# vi: set ft=ruby :

$scriptubuntu = <<SCRIPT
    cd /vagrant
    echo $LDAP_USER
    sudo startxfce4 &
    export DISPLAY=:0.0
    vncserver
    mvn clean install -s $HOME/.m2/settings.xml
SCRIPT


Vagrant.configure('2') do |config|

    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu"
      ubuntu.vm.box_url = "https://s3-eu-west-1.amazonaws.com/tasartifacts/vagrantUI/ubuntu/ubuntu.json"
        ubuntu.vm.provider "virtualbox" do |vb|
          vb.memory = "4500"
          vb.cpus = "2"
          vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
        end
        ubuntu.vm.network "forwarded_port", guest: 5901, host: 5901

        ubuntu.vm.provision 'shell', env: {"LDAP_USER" => "#{ENV['LDAP_USER']}", "LDAP_PASS" => "#{ENV['LDAP_PASS']}"}, inline: $scriptubuntu, privileged: false
    end

end


