//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 01:38:05 PM GMT+02:00 
//


package org.alfresco.utility.extension;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.alfresco.utility.extension package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.alfresco.utility.extension
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtensionPointTestSuit }
     * 
     */
    public ExtensionPointTestSuit createExtensionPointTestSuit() {
        return new ExtensionPointTestSuit();
    }

    /**
     * Create an instance of {@link ExtensionPointTestSuit.TestCases }
     * 
     */
    public ExtensionPointTestSuit.TestCases createExtensionPointTestSuitTestCases() {
        return new ExtensionPointTestSuit.TestCases();
    }

    /**
     * Create an instance of {@link ExtensionPointTestSuit.TestCases.Testcase }
     * 
     */
    public ExtensionPointTestSuit.TestCases.Testcase createExtensionPointTestSuitTestCasesTestcase() {
        return new ExtensionPointTestSuit.TestCases.Testcase();
    }

}
